// Complete APQP process data with all phases and subprocesses
export const apqpPhases = [
  {
    id: 1,
    name: "Plan and Define Program",
    progress: 90,
    status: "in-progress",
    dueDate: "2023-06-30",
    startDate: "2023-01-15",
    description: "Définition des objectifs du projet, des exigences du client et planification initiale.",
    owner: {
      id: 1,
      name: "Jean Dupont",
      avatar: "/placeholder.svg?height=40&width=40",
      initials: "JD",
      role: "Project Manager",
      email: "jean.dupont@example.com",
      phone: "+33 1 23 45 67 89",
    },
    subprocesses: [
      {
        id: 101,
        name: "Voice of the Customer",
        status: "completed",
        progress: 100,
        dueDate: "2023-02-01",
        startDate: "2023-01-15",
        description: "Recueillir et analyser les besoins et attentes du client.",
        owner: { id: 6, name: "Claire Leroy", initials: "CL", role: "Customer Service" },
        documents: [
          { id: 1001, name: "Customer_Requirements.pdf", type: "pdf", date: "2023-01-20" },
          { id: 1002, name: "Customer_Feedback.xlsx", type: "excel", date: "2023-01-25" },
        ],
      },
      {
        id: 102,
        name: "Business Plan/Marketing Strategy",
        status: "completed",
        progress: 100,
        dueDate: "2023-02-05",
        startDate: "2023-01-20",
        description: "Développer la stratégie marketing et le plan d'affaires pour le produit.",
        owner: { id: 1, name: "Jean Dupont", initials: "JD", role: "Project Manager" },
        documents: [
          { id: 1003, name: "Business_Plan.pdf", type: "pdf", date: "2023-01-28" },
          { id: 1004, name: "Marketing_Strategy.pptx", type: "powerpoint", date: "2023-02-01" },
        ],
      },
      {
        id: 103,
        name: "Product/Process Benchmark Data",
        status: "completed",
        progress: 100,
        dueDate: "2023-02-10",
        startDate: "2023-01-25",
        description: "Collecter et analyser les données de référence pour le produit et le processus.",
        owner: { id: 3, name: "Thomas Martin", initials: "TM", role: "R&D Manager" },
        documents: [{ id: 1005, name: "Benchmark_Data.xlsx", type: "excel", date: "2023-02-05" }],
      },
      {
        id: 104,
        name: "Product/Process Assumptions",
        status: "completed",
        progress: 100,
        dueDate: "2023-02-15",
        startDate: "2023-01-30",
        description: "Définir les hypothèses concernant le produit et le processus de fabrication.",
        owner: { id: 2, name: "Marie Laurent", initials: "ML", role: "Process Engineer" },
        documents: [{ id: 1006, name: "Process_Assumptions.docx", type: "word", date: "2023-02-10" }],
      },
      {
        id: 105,
        name: "Product Reliability Studies",
        status: "completed",
        progress: 100,
        dueDate: "2023-02-20",
        startDate: "2023-02-01",
        description: "Réaliser des études de fiabilité du produit.",
        owner: { id: 3, name: "Thomas Martin", initials: "TM", role: "R&D Manager" },
        documents: [{ id: 1007, name: "Reliability_Studies.pdf", type: "pdf", date: "2023-02-15" }],
      },
      {
        id: 106,
        name: "Customer Inputs",
        status: "completed",
        progress: 100,
        dueDate: "2023-02-25",
        startDate: "2023-02-05",
        description: "Recueillir et intégrer les contributions du client.",
        owner: { id: 6, name: "Claire Leroy", initials: "CL", role: "Customer Service" },
        documents: [{ id: 1008, name: "Customer_Inputs.docx", type: "word", date: "2023-02-20" }],
      },
      {
        id: 107,
        name: "Design Goals",
        status: "completed",
        progress: 100,
        dueDate: "2023-03-01",
        startDate: "2023-02-10",
        description: "Définir les objectifs de conception du produit.",
        owner: { id: 3, name: "Thomas Martin", initials: "TM", role: "R&D Manager" },
        documents: [{ id: 1009, name: "Design_Goals.pdf", type: "pdf", date: "2023-02-25" }],
      },
      {
        id: 108,
        name: "Reliability and Quality Goals",
        status: "completed",
        progress: 100,
        dueDate: "2023-03-05",
        startDate: "2023-02-15",
        description: "Établir les objectifs de fiabilité et de qualité pour le produit.",
        owner: { id: 4, name: "Sophie Dubois", initials: "SD", role: "Quality Manager" },
        documents: [{ id: 1010, name: "Quality_Goals.pdf", type: "pdf", date: "2023-03-01" }],
      },
      {
        id: 109,
        name: "Preliminary Bill of Material",
        status: "completed",
        progress: 100,
        dueDate: "2023-03-10",
        startDate: "2023-02-20",
        description: "Développer une liste préliminaire des matériaux nécessaires.",
        owner: { id: 2, name: "Marie Laurent", initials: "ML", role: "Process Engineer" },
        documents: [{ id: 1011, name: "Preliminary_BOM.xlsx", type: "excel", date: "2023-03-05" }],
      },
      {
        id: 110,
        name: "Preliminary Process Flow Chart",
        status: "completed",
        progress: 100,
        dueDate: "2023-03-15",
        startDate: "2023-02-25",
        description: "Créer un diagramme de flux de processus préliminaire.",
        owner: { id: 2, name: "Marie Laurent", initials: "ML", role: "Process Engineer" },
        documents: [{ id: 1012, name: "Process_Flow_Chart.pdf", type: "pdf", date: "2023-03-10" }],
      },
      {
        id: 111,
        name: "Preliminary Listing of Special Product and Process Characteristics",
        status: "in-progress",
        progress: 85,
        dueDate: "2023-03-20",
        startDate: "2023-03-01",
        description: "Identifier les caractéristiques spéciales du produit et du processus.",
        owner: { id: 4, name: "Sophie Dubois", initials: "SD", role: "Quality Manager" },
        documents: [{ id: 1013, name: "Special_Characteristics.xlsx", type: "excel", date: "2023-03-15" }],
      },
      {
        id: 112,
        name: "Product Assurance Plan",
        status: "in-progress",
        progress: 75,
        dueDate: "2023-03-25",
        startDate: "2023-03-05",
        description: "Développer un plan d'assurance produit.",
        owner: { id: 4, name: "Sophie Dubois", initials: "SD", role: "Quality Manager" },
        documents: [{ id: 1014, name: "Product_Assurance_Plan.docx", type: "word", date: "2023-03-20" }],
      },
      {
        id: 113,
        name: "Management Support",
        status: "completed",
        progress: 100,
        dueDate: "2023-03-30",
        startDate: "2023-03-10",
        description: "Obtenir le soutien de la direction pour le projet.",
        owner: { id: 1, name: "Jean Dupont", initials: "JD", role: "Project Manager" },
        documents: [{ id: 1015, name: "Management_Support.pdf", type: "pdf", date: "2023-03-25" }],
      },
    ],
  },
  {
    id: 2,
    name: "Product Design and Development",
    progress: 75,
    status: "in-progress",
    dueDate: "2023-08-30",
    startDate: "2023-03-15",
    description: "Conception et développement du produit selon les spécifications définies.",
    owner: {
      id: 3,
      name: "Thomas Martin",
      avatar: "/placeholder.svg?height=40&width=40",
      initials: "TM",
      role: "R&D Manager",
      email: "thomas.martin@example.com",
      phone: "+33 1 23 45 67 90",
    },
    subprocesses: [
      {
        id: 201,
        name: "Design Failure Mode and Effects Analysis (DFMEA)",
        status: "completed",
        progress: 100,
        dueDate: "2023-04-15",
        startDate: "2023-03-15",
        description: "Réaliser une analyse des modes de défaillance et de leurs effets pour la conception.",
        owner: { id: 3, name: "Thomas Martin", initials: "TM", role: "R&D Manager" },
        documents: [{ id: 2001, name: "DFMEA.xlsx", type: "excel", date: "2023-04-10" }],
      },
      {
        id: 202,
        name: "Design for Manufacturability and Assembly",
        status: "completed",
        progress: 100,
        dueDate: "2023-04-30",
        startDate: "2023-03-30",
        description: "Optimiser la conception pour la fabrication et l'assemblage.",
        owner: { id: 2, name: "Marie Laurent", initials: "ML", role: "Process Engineer" },
        documents: [{ id: 2002, name: "DFM_Analysis.pdf", type: "pdf", date: "2023-04-25" }],
      },
      {
        id: 203,
        name: "Design Verification",
        status: "completed",
        progress: 100,
        dueDate: "2023-05-15",
        startDate: "2023-04-15",
        description: "Vérifier que la conception répond aux exigences spécifiées.",
        owner: { id: 3, name: "Thomas Martin", initials: "TM", role: "R&D Manager" },
        documents: [{ id: 2003, name: "Design_Verification.pdf", type: "pdf", date: "2023-05-10" }],
      },
      {
        id: 204,
        name: "Design Reviews",
        status: "completed",
        progress: 100,
        dueDate: "2023-05-30",
        startDate: "2023-05-01",
        description: "Conduire des revues de conception avec les parties prenantes.",
        owner: { id: 3, name: "Thomas Martin", initials: "TM", role: "R&D Manager" },
        documents: [{ id: 2004, name: "Design_Review_Minutes.pdf", type: "pdf", date: "2023-05-25" }],
      },
      {
        id: 205,
        name: "Prototype Build – Control Plan",
        status: "in-progress",
        progress: 90,
        dueDate: "2023-06-15",
        startDate: "2023-05-15",
        description: "Développer un plan de contrôle pour la construction des prototypes.",
        owner: { id: 4, name: "Sophie Dubois", initials: "SD", role: "Quality Manager" },
        documents: [{ id: 2005, name: "Prototype_Control_Plan.docx", type: "word", date: "2023-06-10" }],
      },
      {
        id: 206,
        name: "Engineering Drawings (Including Math Data)",
        status: "in-progress",
        progress: 85,
        dueDate: "2023-06-30",
        startDate: "2023-05-30",
        description: "Créer les dessins techniques détaillés du produit.",
        owner: { id: 3, name: "Thomas Martin", initials: "TM", role: "R&D Manager" },
        documents: [{ id: 2006, name: "Engineering_Drawings.pdf", type: "pdf", date: "2023-06-25" }],
      },
      {
        id: 207,
        name: "Engineering Specifications",
        status: "in-progress",
        progress: 80,
        dueDate: "2023-07-15",
        startDate: "2023-06-15",
        description: "Documenter les spécifications techniques détaillées.",
        owner: { id: 3, name: "Thomas Martin", initials: "TM", role: "R&D Manager" },
        documents: [{ id: 2007, name: "Engineering_Specs.docx", type: "word", date: "2023-07-10" }],
      },
      {
        id: 208,
        name: "Material Specifications",
        status: "in-progress",
        progress: 75,
        dueDate: "2023-07-30",
        startDate: "2023-06-30",
        description: "Définir les spécifications détaillées des matériaux.",
        owner: { id: 3, name: "Thomas Martin", initials: "TM", role: "R&D Manager" },
        documents: [{ id: 2008, name: "Material_Specs.docx", type: "word", date: "2023-07-25" }],
      },
      {
        id: 209,
        name: "Drawing and Specification Changes",
        status: "in-progress",
        progress: 60,
        dueDate: "2023-08-15",
        startDate: "2023-07-15",
        description: "Gérer les modifications des dessins et des spécifications.",
        owner: { id: 3, name: "Thomas Martin", initials: "TM", role: "R&D Manager" },
        documents: [{ id: 2009, name: "Drawing_Changes.xlsx", type: "excel", date: "2023-08-10" }],
      },
      {
        id: 210,
        name: "New Equipment, Tooling and Facilities Requirements",
        status: "in-progress",
        progress: 50,
        dueDate: "2023-08-30",
        startDate: "2023-07-30",
        description: "Identifier les besoins en nouveaux équipements, outillages et installations.",
        owner: { id: 5, name: "Pierre Moreau", initials: "PM", role: "Production Manager" },
        documents: [{ id: 2010, name: "Equipment_Requirements.xlsx", type: "excel", date: "2023-08-25" }],
      },
      {
        id: 211,
        name: "Special Product and Process Characteristics",
        status: "not-started",
        progress: 0,
        dueDate: "2023-09-15",
        startDate: "2023-08-15",
        description: "Documenter les caractéristiques spéciales du produit et du processus.",
        owner: { id: 4, name: "Sophie Dubois", initials: "SD", role: "Quality Manager" },
      },
      {
        id: 212,
        name: "Gages/Testing Equipment Requirements",
        status: "not-started",
        progress: 0,
        dueDate: "2023-09-30",
        startDate: "2023-08-30",
        description: "Définir les exigences pour les équipements de test et de mesure.",
        owner: { id: 4, name: "Sophie Dubois", initials: "SD", role: "Quality Manager" },
      },
      {
        id: 213,
        name: "Team Feasibility Commitment and Management Support",
        status: "not-started",
        progress: 0,
        dueDate: "2023-10-15",
        startDate: "2023-09-15",
        description: "Obtenir l'engagement de l'équipe sur la faisabilité et le soutien de la direction.",
        owner: { id: 1, name: "Jean Dupont", initials: "JD", role: "Project Manager" },
      },
    ],
  },
  {
    id: 3,
    name: "Process Design and Development",
    progress: 40,
    status: "in-progress",
    dueDate: "2023-12-31",
    startDate: "2023-06-01",
    description: "Conception et développement du processus de fabrication.",
    owner: {
      id: 2,
      name: "Marie Laurent",
      avatar: "/placeholder.svg?height=40&width=40",
      initials: "ML",
      role: "Process Engineer",
      email: "marie.laurent@example.com",
      phone: "+33 1 23 45 67 91",
    },
    subprocesses: [
      {
        id: 301,
        name: "Packaging Standards",
        status: "completed",
        progress: 100,
        dueDate: "2023-07-15",
        startDate: "2023-06-01",
        description: "Définir les normes d'emballage pour le produit.",
        owner: { id: 5, name: "Pierre Moreau", initials: "PM", role: "Production Manager" },
        documents: [{ id: 3001, name: "Packaging_Standards.pdf", type: "pdf", date: "2023-07-10" }],
      },
      {
        id: 302,
        name: "Product/Process Quality System Review",
        status: "completed",
        progress: 100,
        dueDate: "2023-07-30",
        startDate: "2023-06-15",
        description: "Examiner le système qualité pour le produit et le processus.",
        owner: { id: 4, name: "Sophie Dubois", initials: "SD", role: "Quality Manager" },
        documents: [{ id: 3002, name: "Quality_System_Review.pdf", type: "pdf", date: "2023-07-25" }],
      },
      {
        id: 303,
        name: "Process Flow Chart",
        status: "completed",
        progress: 100,
        dueDate: "2023-08-15",
        startDate: "2023-07-01",
        description: "Créer un diagramme de flux détaillé du processus de fabrication.",
        owner: { id: 2, name: "Marie Laurent", initials: "ML", role: "Process Engineer" },
        documents: [{ id: 3003, name: "Process_Flow_Chart.pdf", type: "pdf", date: "2023-08-10" }],
      },
      {
        id: 304,
        name: "Floor Plan Layout",
        status: "in-progress",
        progress: 90,
        dueDate: "2023-08-30",
        startDate: "2023-07-15",
        description: "Concevoir l'aménagement de l'espace de production.",
        owner: { id: 5, name: "Pierre Moreau", initials: "PM", role: "Production Manager" },
        documents: [{ id: 3004, name: "Floor_Plan.pdf", type: "pdf", date: "2023-08-25" }],
      },
      {
        id: 305,
        name: "Characteristics Matrix",
        status: "in-progress",
        progress: 80,
        dueDate: "2023-09-15",
        startDate: "2023-08-01",
        description: "Développer une matrice des caractéristiques du produit et du processus.",
        owner: { id: 4, name: "Sophie Dubois", initials: "SD", role: "Quality Manager" },
        documents: [{ id: 3005, name: "Characteristics_Matrix.xlsx", type: "excel", date: "2023-09-10" }],
      },
      {
        id: 306,
        name: "Process Failure Mode and Effects Analysis (PFMEA)",
        status: "in-progress",
        progress: 70,
        dueDate: "2023-09-30",
        startDate: "2023-08-15",
        description: "Réaliser une analyse des modes de défaillance et de leurs effets pour le processus.",
        owner: { id: 2, name: "Marie Laurent", initials: "ML", role: "Process Engineer" },
        documents: [{ id: 3006, name: "PFMEA.xlsx", type: "excel", date: "2023-09-25" }],
      },
      {
        id: 307,
        name: "Pre-Launch Control Plan",
        status: "in-progress",
        progress: 60,
        dueDate: "2023-10-15",
        startDate: "2023-09-01",
        description: "Développer un plan de contrôle pour la phase de pré-lancement.",
        owner: { id: 4, name: "Sophie Dubois", initials: "SD", role: "Quality Manager" },
        documents: [{ id: 3007, name: "Pre-Launch_Control_Plan.docx", type: "word", date: "2023-10-10" }],
      },
      {
        id: 308,
        name: "Process Instructions",
        status: "in-progress",
        progress: 50,
        dueDate: "2023-10-30",
        startDate: "2023-09-15",
        description: "Créer des instructions détaillées pour le processus de fabrication.",
        owner: { id: 2, name: "Marie Laurent", initials: "ML", role: "Process Engineer" },
        documents: [{ id: 3008, name: "Process_Instructions.docx", type: "word", date: "2023-10-25" }],
      },
      {
        id: 309,
        name: "Measurement Systems Analysis Plan",
        status: "in-progress",
        progress: 40,
        dueDate: "2023-11-15",
        startDate: "2023-10-01",
        description: "Planifier l'analyse des systèmes de mesure.",
        owner: { id: 4, name: "Sophie Dubois", initials: "SD", role: "Quality Manager" },
        documents: [{ id: 3009, name: "MSA_Plan.docx", type: "word", date: "2023-11-10" }],
      },
      {
        id: 310,
        name: "Preliminary Process Capability Study Plan",
        status: "not-started",
        progress: 0,
        dueDate: "2023-11-30",
        startDate: "2023-10-15",
        description: "Planifier l'étude préliminaire de la capabilité du processus.",
        owner: { id: 2, name: "Marie Laurent", initials: "ML", role: "Process Engineer" },
      },
      {
        id: 311,
        name: "Packaging Specifications",
        status: "not-started",
        progress: 0,
        dueDate: "2023-12-15",
        startDate: "2023-11-01",
        description: "Définir les spécifications détaillées d'emballage.",
        owner: { id: 5, name: "Pierre Moreau", initials: "PM", role: "Production Manager" },
      },
      {
        id: 312,
        name: "Management Support",
        status: "not-started",
        progress: 0,
        dueDate: "2023-12-31",
        startDate: "2023-11-15",
        description: "Obtenir le soutien de la direction pour la phase de conception du processus.",
        owner: { id: 1, name: "Jean Dupont", initials: "JD", role: "Project Manager" },
      },
    ],
  },
  {
    id: 4,
    name: "Product and Process Validation",
    progress: 10,
    status: "not-started",
    dueDate: "2024-04-30",
    startDate: "2024-01-01",
    description: "Validation du produit et du processus de fabrication.",
    owner: {
      id: 4,
      name: "Sophie Dubois",
      avatar: "/placeholder.svg?height=40&width=40",
      initials: "SD",
      role: "Quality Manager",
      email: "sophie.dubois@example.com",
      phone: "+33 1 23 45 67 92",
    },
    subprocesses: [
      {
        id: 401,
        name: "Production Trial Run",
        status: "not-started",
        progress: 0,
        dueDate: "2024-01-31",
        startDate: "2024-01-01",
        description: "Réaliser un essai de production.",
        owner: { id: 5, name: "Pierre Moreau", initials: "PM", role: "Production Manager" },
      },
      {
        id: 402,
        name: "Measurement Systems Evaluation",
        status: "not-started",
        progress: 0,
        dueDate: "2024-02-15",
        startDate: "2024-01-15",
        description: "Évaluer les systèmes de mesure.",
        owner: { id: 4, name: "Sophie Dubois", initials: "SD", role: "Quality Manager" },
      },
      {
        id: 403,
        name: "Preliminary Process Capability Study",
        status: "not-started",
        progress: 0,
        dueDate: "2024-02-29",
        startDate: "2024-02-01",
        description: "Réaliser une étude préliminaire de la capabilité du processus.",
        owner: { id: 2, name: "Marie Laurent", initials: "ML", role: "Process Engineer" },
      },
      {
        id: 404,
        name: "Production Part Approval",
        status: "not-started",
        progress: 0,
        dueDate: "2024-03-15",
        startDate: "2024-02-15",
        description: "Obtenir l'approbation des pièces de production.",
        owner: { id: 4, name: "Sophie Dubois", initials: "SD", role: "Quality Manager" },
      },
      {
        id: 405,
        name: "Production Validation Testing",
        status: "not-started",
        progress: 0,
        dueDate: "2024-03-31",
        startDate: "2024-03-01",
        description: "Effectuer des tests de validation de la production.",
        owner: { id: 4, name: "Sophie Dubois", initials: "SD", role: "Quality Manager" },
      },
      {
        id: 406,
        name: "Packaging Evaluation",
        status: "not-started",
        progress: 0,
        dueDate: "2024-04-15",
        startDate: "2024-03-15",
        description: "Évaluer les solutions d'emballage pour le produit final.",
        owner: { id: 5, name: "Pierre Moreau", initials: "PM", role: "Production Manager" },
      },
      {
        id: 407,
        name: "Production Control Plan",
        status: "not-started",
        progress: 0,
        dueDate: "2024-04-30",
        startDate: "2024-04-01",
        description: "Développer un plan de contrôle pour la production en série.",
        owner: { id: 4, name: "Sophie Dubois", initials: "SD", role: "Quality Manager" },
      },
      {
        id: 408,
        name: "Quality Planning Sign-Off and Management Support",
        status: "not-started",
        progress: 0,
        dueDate: "2024-04-30",
        startDate: "2024-04-15",
        description: "Obtenir la signature finale du plan qualité et le soutien de la direction.",
        owner: { id: 1, name: "Jean Dupont", initials: "JD", role: "Project Manager" },
      },
    ],
  },
  {
    id: 5,
    name: "Feedback, Assessment and Corrective Action",
    progress: 0,
    status: "not-started",
    dueDate: "2024-06-30",
    startDate: "2024-05-01",
    description: "Évaluation des retours et mise en place d'actions correctives.",
    owner: {
      id: 1,
      name: "Jean Dupont",
      avatar: "/placeholder.svg?height=40&width=40",
      initials: "JD",
      role: "Project Manager",
      email: "jean.dupont@example.com",
      phone: "+33 1 23 45 67 89",
    },
    subprocesses: [
      {
        id: 501,
        name: "Reduced Variation",
        status: "not-started",
        progress: 0,
        dueDate: "2024-05-15",
        startDate: "2024-05-01",
        description: "Mettre en œuvre des actions pour réduire la variation du processus.",
        owner: { id: 2, name: "Marie Laurent", initials: "ML", role: "Process Engineer" },
      },
      {
        id: 502,
        name: "Customer Satisfaction",
        status: "not-started",
        progress: 0,
        dueDate: "2024-05-31",
        startDate: "2024-05-15",
        description: "Évaluer et améliorer la satisfaction client.",
        owner: { id: 6, name: "Claire Leroy", initials: "CL", role: "Customer Service" },
      },
      {
        id: 503,
        name: "Delivery and Service",
        status: "not-started",
        progress: 0,
        dueDate: "2024-06-15",
        startDate: "2024-06-01",
        description: "Optimiser le service client et les délais de livraison.",
        owner: { id: 5, name: "Pierre Moreau", initials: "PM", role: "Production Manager" },
      },
    ],
  },
]

// Team members for filtering
export const teamMembers = [
  {
    id: 1,
    name: "Jean Dupont",
    avatar: "/placeholder.svg?height=40&width=40",
    initials: "JD",
    role: "Project Manager",
    department: "Management",
    email: "jean.dupont@example.com",
    phone: "+33 1 23 45 67 89",
  },
  {
    id: 2,
    name: "Marie Laurent",
    avatar: "/placeholder.svg?height=40&width=40",
    initials: "ML",
    role: "Process Engineer",
    department: "Engineering",
    email: "marie.laurent@example.com",
    phone: "+33 1 23 45 67 91",
  },
  {
    id: 3,
    name: "Thomas Martin",
    avatar: "/placeholder.svg?height=40&width=40",
    initials: "TM",
    role: "R&D Manager",
    department: "R&D",
    email: "thomas.martin@example.com",
    phone: "+33 1 23 45 67 90",
  },
  {
    id: 4,
    name: "Sophie Dubois",
    avatar: "/placeholder.svg?height=40&width=40",
    initials: "SD",
    role: "Quality Manager",
    department: "Quality",
    email: "sophie.dubois@example.com",
    phone: "+33 1 23 45 67 92",
  },
  {
    id: 5,
    name: "Pierre Moreau",
    avatar: "/placeholder.svg?height=40&width=40",
    initials: "PM",
    role: "Production Manager",
    department: "Production",
    email: "pierre.moreau@example.com",
    phone: "+33 1 23 45 67 93",
  },
  {
    id: 6,
    name: "Claire Leroy",
    avatar: "/placeholder.svg?height=40&width=40",
    initials: "CL",
    role: "Customer Service",
    department: "Sales",
    email: "claire.leroy@example.com",
    phone: "+33 1 23 45 67 94",
  },
]

// Projects for filtering
export const projects = [
  { id: 1, name: "Projet A - Composant Automobile" },
  { id: 2, name: "Projet B - Système Électronique" },
  { id: 3, name: "Projet C - Pièce Plastique" },
  { id: 4, name: "Projet D - Assemblage Mécanique" },
]

// Departments for filtering
export const departments = [
  { id: 1, name: "Management" },
  { id: 2, name: "Engineering" },
  { id: 3, name: "R&D" },
  { id: 4, name: "Quality" },
  { id: 5, name: "Production" },
  { id: 6, name: "Sales" },
]
